GRASS_TYPE_START = 1
GRASS_TYPE_END = 5

MONSTERS = [
    {
        "name" : "unknown",
        "index" : 0,
        "level_start" : 1,
        "base_health" : 5,
        "base_attack" : 5,
        "monster_type" : "G",
    },
    {
        "name" : "chick",
        "index" : 1,
        "level_start" : 1,
        "base_health" : 5,
        "base_attack" : 5,
        "monster_type" : "G",
        "evolves_to" : 2,
    },
    {
        "name": "chicken",
        "index": 2,
        "level_start": 5,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": 3,
    },
    {
        "name": "elephent",
        "index": 3,
        "level_start": 15,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": None,
    },
    {
        "name": "frog",
        "index": 4,
        "level_start": 1,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": 5,
    },
    {
        "name": "snake",
        "index": 5,
        "level_start": 5,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": 6,
    },
    {
        "name": "crocodile",
        "index": 6,
        "level_start": 15,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": None,
    },
    {
        "name": "rabbit",
        "index": 7,
        "level_start": 1,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": 8,
    },
    {
        "name": "dog",
        "index": 8,
        "level_start": 5,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": 9,
    },
    {
        "name": "rhino",
        "index": 9,
        "level_start": 15,
        "base_health": 5,
        "base_attack": 5,
        "monster_type": "G",
        "evolves_to": None,
    },
]

